### ISSUE TITLE
Bug in ridge regression with induct_used=1?

### ISSUE THREAD

**Issue by ESaundersNano** [ciuccislab/pyDRTtools#7]
Thank you for the great module. I have noticed that if induct_used=1 when calling simple_run in a notebook or by selecting "with inductive element" in the GUI, there is an issue forming the G matrix and an error is caused.

**Comment by ESaundersNano** [comment]
This issue is at least apparent if the example dataset from the tutorial is used, but also happens when I use my data.

**Comment by ciuccislab** [comment]
The issue arises from matrix mismatch in a line of code that enforces non-negativity constraint. The issue has been fixed in the line of code below. Nonetheless, a new version of tutorial will be released with the new/latest version of pyDRTtools. You can run main GUI, there will be no issue again. Thank you.

![image](https://github.com/ciuccislab/pyDRTtools/assets/57649983/bcd8fa72-1824-40c8-8750-19398ff9ccdc)
