### ISSUE TITLE
Failed running pyDRTtools/tutorial /how_to_import_pyDRTtools_modules_.ipynb

### ISSUE THREAD

**Issue by vantasyoscar** [ciuccislab/pyDRTtools#8]
Following this tutorial, I failed at the cell:
```python
entry = simple_run(eis_data)
``` 
with the error followed
![image](https://github.com/ciuccislab/pyDRTtools/assets/69444912/28abcb27-bec0-474d-801e-208128699305)
I wonder what's wrong with it. Thanks a lot.

**Comment by ciuccislab** [comment]
The issue arises from matrix mismatch in a line of code to enforce non-negativity constraint. The issue has been fixed in the line of code below. Nonetheless, a new version of tutorial will be released with the new latest version of pyDRTtools. You can run main GUI, there will be no issue again. 



![image](https://github.com/ciuccislab/pyDRTtools/assets/57649983/6af69b9a-efa8-4fef-a3cf-a28397009c89)
